### ISSUE TITLE
The tool fails to scan partially in Windows 8

### ISSUE THREAD

**Issue by Graos** [Forescout/project-memoria-detector#12]
I ran the tool against my DUT with IP address 192.168.0.2. ICMP scan was successful with [No Match] but the next scan on TCP fails with the following error. What is that WinError 2 file ? How to resolve this further ?

192.168.0.2 is alive
        ICMP => Unknown (No match)

ERROR: [WinError 2] The system cannot find the file specified

Traceback (most recent call last):
  File "project-memoria-detector.py", line 821, in <module>
    (stack_name, match_confidence) = tcpv4_probe(dst_host, tcp_dport, interface,
 [], fw, timeout)
  File "project-memoria-detector.py", line 717, in tcpv4_probe
    subprocess.check_call(['iptables', '-D', 'OUTPUT', '-p', 'tcp',
  File "C:\Programs\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Programs\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Programs\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Programs\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by standash** [comment]
Hi @Graos, thank you for your comment. Indeed, I have not tested the script in Windows. I have fixed the corresponding option, so please pull the latest commit, and try running the script adding the "--skip-iptables" flag. Let me know if it works for you now.

**Comment by Graos** [comment]
I tried python project-memoria-detector.py -iptables 192.168.0.2 and i get the following errors
192.168.0.2 is alive
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Programs\lib\site-packages\scapy\arch\windows\__init__.py", line 693,
 in dev_from_name
    return next(iface for iface in six.itervalues(self)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\lib\site-packages\scapy\arch\windows\__init__.py", line 772,
 in pcapname
    return IFACES.dev_from_name(dev).pcap_name
  File "C:\Programs\lib\site-packages\scapy\arch\windows\__init__.py", line 696,
 in dev_from_name
    raise ValueError("Unknown network interface %r" % name)
ValueError: Unknown network interface 'ptables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\lib\site-packages\scapy\arch\windows\__init__.py", line 701,
 in dev_from_pcapname
    return next(iface for iface in six.itervalues(self)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Programs\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Programs\lib\site-packages\scapy\sendrecv.py", line 906, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "C:\Programs\lib\site-packages\scapy\arch\pcapdnet.py", line 301, in __in
it__
    self.ins = open_pcap(iface, MTU, self.promisc, 100,
  File "C:\Programs\lib\site-packages\scapy\arch\windows\__init__.py", line 799,
 in open_pcap
    iface_pcap_name = pcapname(iface)
  File "C:\Programs\lib\site-packages\scapy\arch\windows\__init__.py", line 774,
 in pcapname
    return IFACES.dev_from_pcapname(dev).pcap_name
  File "C:\Programs\lib\site-packages\scapy\arch\windows\__init__.py", line 704,
 in dev_from_pcapname
    raise ValueError("Unknown pypcap network interface %r" % pcap_name)
ValueError: Unknown pypcap network interface 'ptables'
Traceback (most recent call last):
  File "C:\Programs\lib\site-packages\scapy\sendrecv.py", line 1017, in stop
    self.stop_cb()
AttributeError: 'AsyncSniffer' object has no attribute 'stop_cb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "project-memoria-detector.py", line 812, in <module>
    (stack_name, match_confidence) = icmpv4_probe(dst_host, timeout)
  File "project-memoria-detector.py", line 252, in icmpv4_probe
    pkts = t.stop()
  File "C:\Programs\lib\site-packages\scapy\sendrecv.py", line 1019, in stop
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Unsupported (offline or unsupported socket)

**Comment by Graos** [comment]
--skip option is not working

**Comment by standash** [comment]
Hi, from what I see the problem seems to be on your side, Here's how you should run your script: 
![image](https://user-images.githubusercontent.com/8415231/128838226-3cfc56ef-bf77-4ca3-ba10-5a5f00a58b84.png)

**Comment by Graos** [comment]
I get the following errors if i use in the way you suggested

py -3 project-memoria-detector.py 192.168.0.2 --skip-iptables
usage: project-memoria-detector.py [-h] [-p [TCP_DPORT]]
                                   [--http-port [HTTP_DPORT]]
                                   [--ssh-port [SSH_DPORT]]
                                   [--ftp-port [FTP_DPORT]] [-t [TIMEOUT]]
                                   [-i [INTERFACE]] [-og [GW]] [-fw [FW]]
                                   [-f [IN_FILE]] [-o [OUT_CSV]]
                                   [ip_dst]
project-memoria-detector.py: error: unrecognized arguments: --skip-iptables

**Comment by standash** [comment]
This is weird. Can you try a shorthand version of this option instead? 
![image](https://user-images.githubusercontent.com/8415231/128840618-74254e3f-4d60-4c5d-ba37-292ff42b65f0.png)

UPDATE: please do not forget to pull the latest commit before doing that.

**Comment by Graos** [comment]
Same result even after i use the shorthand version.

**Comment by standash** [comment]
Hmm, have you pulled the latest commit from the repository?

**Comment by Graos** [comment]
Yes I did. Meanwhile i tried in Ubuntu distribution. It works fine without any issues.

**Comment by standash** [comment]
Sorry, but this cannot be, I have removed the "FW" option in the latest commit: 
![image](https://user-images.githubusercontent.com/8415231/128841542-5edd261e-7858-4855-8b8d-3c7170c364a1.png)

Anyway, I am happy it works for you now :)

**Comment by Graos** [comment]
Sorry i did a pull but for some reason the code base is not updated. I tried again and now it works in windows as well. Thanks for your support.

**Comment by standash** [comment]
> Sorry i did a pull but for some reason the code base is not updated. I tried again and now it works in windows as well. Thanks for your support.

No problem at all, I am happy to help! Please don't hesitate to report other issues, questions, or comments on usability :)
