### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by manilaboy1vic** [Forescout/project-memoria-detector#7]
Thanks for putting this tool out there.

I am running into traceback when attempting to run the tool.

I created this symlink

lrwxrwxrwx  1 root root            16 Apr 14 10:46 python -> /usr/bin/python3

python -V                                                                                                                                
Python 3.8.5

scapy                                                                                                                                   
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
INFO: No IPv6 support in kernel
                                      
                     aSPY//YASa       
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
 ayp ayyyyyyySCP//Pp           syY//C    | **Version 2.4.4**

sudo -E python project-memoria-detector.py -ip_dst 192.168.1.3 -p 80 -i re0               
                                              
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vic/.local/lib/python3.8/site-packages/scapy/sendrecv.py", line 906, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/home/vic/.local/lib/python3.8/site-packages/scapy/arch/linux.py", line 411, in __init__
    set_promisc(self.ins, self.iface)
  File "/home/vic/.local/lib/python3.8/site-packages/scapy/arch/linux.py", line 147, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/home/vic/.local/lib/python3.8/site-packages/scapy/arch/linux.py", line 360, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/home/vic/.local/lib/python3.8/site-packages/scapy/arch/common.py", line 31, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device
Traceback (most recent call last):
  File "/home/vic/.local/lib/python3.8/site-packages/scapy/sendrecv.py", line 1017, in stop
    self.stop_cb()
AttributeError: 'AsyncSniffer' object has no attribute 'stop_cb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "project-memoria-detector.py", line 832, in <module>
    (stack_name_icmp, match_icmp) = icmpv4_probe(dst_host, timeout)
  File "project-memoria-detector.py", line 260, in icmpv4_probe
    pkts = t.stop()
  File "/home/vic/.local/lib/python3.8/site-packages/scapy/sendrecv.py", line 1019, in stop
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Unsupported (offline or unsupported socket)

**Comment by standash** [comment]
Hi @manilaboy1vic, I have Scapy 2.4.4 and Python 3.9.2, and I can't reproduce your issue. Maybe, something is wrong with your dependencies? You could also try installing dependencies with [virtualenv](https://pypi.org/project/virtualenv/).

**Comment by manilaboy1vic** [comment]
This can be close I found the issue.
